[package]
name = "my-first-rust"
version = "0.1.0"
authors = ["hana <asufanah@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.4.3"
anyhow = "1.0"
thiserror = "1.0"
dotenv = "0.14.1"
diesel = { version = "1.4.1", features = ["sqlite"] }
diesel-derive-newtype = "0.1.2"
